### ISSUE TITLE
make install fails on ubuntu

### ISSUE THREAD

**Issue by vadamoto** [bigartm/bigartm#564] opened 2016-05-13 18:55 UTC
error: Setup script exited with error: Command "x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Inumpy/core/include -Ibuild/src.linux-x86_64-2.7/numpy/core/include/numpy -I/usr/include/python2.7 -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -Ibuild/src.linux-x86_64-2.7/numpy/core/src/private -c build/src.linux-x86_64-2.7/numpy/core/src/npymath/ieee754.c -o build/temp.linux-x86_64-2.7/build/src.linux-x86_64-2.7/numpy/core/src/npymath/ieee754.o" failed with exit status 1numpy/core/src/npymath/ieee754.c.src:7:29: fatal error: npy_math_common.h: No such file or directory

And I don't even need numpy, I already installed it by pip install AND by anaconda :(

**Comment by JeanPaulShapo** [comment] 2016-05-13 20:52
@vadamoto could you provide full log of building, if it's possible?

**Comment by sashafrey** [comment] 2016-05-13 22:50
@vadamoto yes, full log would be really helpful. I'm surprised that ``make install`` of BigARTM triggers a build of numpy.
Do you follow these intructions? http://docs.bigartm.org/en/latest/installation/linux.html

**Comment by vadamoto** [comment] 2016-05-14 07:47
> Do you follow these intructions?

Yes, I did. After my comment, I managed to install bigartm by doing "apt-get install python-numpy",
so today it took some effort to reproduce "fatal error: npy_math_common.h: No such file or directory". 

[bigartm.3.cmake.txt](https://github.com/bigartm/bigartm/files/264416/bigartm.3.cmake.txt)
[bigartm.3.install.txt](https://github.com/bigartm/bigartm/files/264417/bigartm.3.install.txt)
[bigartm.3.make.txt](https://github.com/bigartm/bigartm/files/264418/bigartm.3.make.txt)

**Comment by sashafrey** [comment] 2016-05-14 11:07
@vadamoto I see. This is related to our [setup.py](https://github.com/bigartm/bigartm/blob/master/python/setup.py) file, which specifies that our python module ``bigartm`` depends on ``numpy``:
```
setup(
    name='bigartm',
    version='0.8.0',
    packages=find_packages(),
    install_requires=[
        'pandas',
        'numpy'
    ],
    cmdclass={'build': build},
)
```
I don't understand why python setup fails to recognize that you already have numpy on your machine (as part of anaconda). @JeanPaulShapo Any ideas why this can happen?

@vadamoto I can't reproduce this issue, and the same steps work well on ``travis-ci``. Given that there is a simple workaround I believe we should close this issue. But if you have any suggested code changes that may help in this case --- please, share, we can put them in and see if it helps.

**Comment by vadamoto** [comment] 2016-05-14 18:10
Only it's not working:
```
$ python
Python 2.7.11 |Anaconda 2.5.0 (64-bit)| (default, Dec  6 2015, 18:08:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import artm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named artm

```

**Comment by sashafrey** [comment] 2016-05-14 18:23
@vadamoto Ok, there is another way of installing python API of bigartm, which we used up to v0.7.4. Then, in v0.7.5 we instroduce ``python setup.py install`` -- apparently it still has some remaining issues which we need to address. 

Could you please try old instructions and let us know if they worked for you? 
http://docs.bigartm.org/en/stable/tutorials/linux_basic.html
```
# Step 1 - add BigARTM python bindings to PYTHONPATH
export PYTHONPATH=~/bigartm/python:$PYTHONPATH

# Step 2 - install google protobuf
cd ~/bigartm
cp build/3rdparty/protobuf-cmake/protoc/protoc 3rdparty/protobuf/src/
cd 3rdparty/protobuf/python
python setup.py build
sudo python setup.py install

# Step 3 - point ARTM_SHARED_LIBRARY variable to libartm.so (libartm.dylib) location
export ARTM_SHARED_LIBRARY=~/bigartm/build/src/artm/libartm.so        # for linux
export ARTM_SHARED_LIBRARY=~/bigartm/build/src/artm/libartm.dylib     # for Mac OS X
```

**Comment by vadamoto** [comment] 2016-05-14 18:31
This works! Thank you :)

**Comment by sashafrey** [comment] 2016-05-14 18:33
Great! Please let me know if there are other problems! :)

**Comment by JeanPaulShapo** [comment] 2016-05-19 21:52
On my laptop with Fedora 22 there no error during performing fresh install of BigARTM + NumPy + Pandas, however I could reproduce the same behaviour on Ubuntu 14.04 LTS. Maybe this problem heavily depends on linux distribution and software configuration.

**Comment by JeanPaulShapo** [comment] 2016-05-19 21:53
Seems that NumPy works badly with `install_requires` option. There are a lot of github issues when NumPy couldn't be installed properly as dependency.

Some possible workarounds present [here](https://github.com/nengo/nengo/issues/508#issuecomment-64962892) and [here](https://github.com/numpy/numpy/issues/2434#issuecomment-65252402).

The PR #569 (possibly) fixes this problem.
@vadamoto If you had time and can perform clean install using `virtualenv`, I strongly recommend you to check, whether this change fixes this problem. On my Ubuntu 14.04 LTS this solution works. I can only guess how can it work on your system.

**Comment by ofrei** [comment] 2016-12-12 00:27
This issue seems to be fixed.

**Closed by ofrei** 2016-12-12 00:27 UTC
Labels: build
