### ISSUE TITLE
macOS build fail: gflags_LIBRARIES is set to NOTFOUND.

### ISSUE THREAD

**Issue by ivanychev** [bigartm/bigartm#865] opened 2018-02-07 13:28 UTC
I'm trying to build the library using standard tutorial on my machine

* masOS 10.13.3
* cmake 3.10.2
* boost 1.66.0

I get following error when I'm trying to generate a makefile via `cmake ..` within the `build/` directory.

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
gflags_LIBRARIES
    linked by target "glog" in directory /Users/iv/code/bigartm/3rdparty/glog
```

Since I've tried building it on Ubuntu and succeeded, I suspect there's something wrong with macOS. Does anyone encounter the same issues?

**Comment by niwtr** [comment] 2018-03-08 07:49
Encountered the same problem. Did you solved that? Please let me know if so.

**Comment by melodywolk** [comment] 2018-04-02 23:09
Any update on this issue?

**Comment by MichaelSolotky** [comment] 2018-10-27 21:28
Hi, @ivanychev, @niwtr, @melodywolk
Since that time you were writing a lot of things changed in CMakeList.txt.
Could you please try to compile the latest master version and check if the trouble disappeared? I actually have macOS too and I can't reproduce this behavior.

**Comment by niwtr** [comment] 2018-10-30 01:03
Hi, @MichaelSolotky 
I acknowledge that this bug is fixed, build succeeded. Congratulations and thanks for the jobs you've done.

**Comment by MichaelSolotky** [comment] 2018-10-30 07:02
It's cool.
I close this issue then.
If anyone encounters a similar problem please reopen this issue and we'll try to help you.

**Closed by MichaelSolotky** 2018-10-30 07:02 UTC
